services:

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: $DATABASE_URL
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        POSTGRES_DB: $POSTGRES_DB
        NEXTAUTH_URL: $NEXTAUTH_URL 
        GOOGLE_CLIENT_ID: $GOOGLE_CLIENT_ID
        GOOGLE_CLIENT_SECRET: $GOOGLE_CLIENT_SECRET 
        NODE_ENV: $NODE_ENV 
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    env_file: ".env"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && npx prisma migrate reset --force && npm run dev"
    networks:
      - a11y-network

  db:
    image: postgres:latest
    env_file: ".env"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - a11y-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  a11y-network:

volumes:
  postgres_data: