name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker compose build -e NODE_ENV="development" -e DATABASE_URL=${{ secrets.DATABASE_URL }} -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} -e NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} -e NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} -e GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} -e GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
